feat : 로그인 유저정보 조회 및 홈, 게시판, 퀴즈목록 기본 틀 생성
Battle-Q/battleq-web pull request #3
Opened 2023-06-29 09:47 UTC by gyucheolshin

### 작업내역
- 로그인 시 홈 이동 및 유저 정보 조회
- 게시판(공지사항, 자유게시판) 틀 생성
- 퀴즈목록 틀 생성
- 홈 틀 생성 (pin 6자리 입력 시 버튼 활성화)

### 리뷰필요사항

2023-07-02 09:06 UTC, rhtld123 requested changes
고생하셨습니다~ 코멘트 확인 부탁드려요

2023-07-02 09:06 UTC, rhtld123 commented on src/components/LoginPage.tsx
> +        localStorage.setItem("pwd", data.pwd);
비밀번호는 저장하면 안될 것 같아요
```suggestion

```

2023-07-03 13:25 UTC, HoYeonHwang reviewed
고생하셨습니다. 
이번 battleq 새로 시작하면서 변경된 서버 api쪽 명세 맞추는 과정도 따로 필요할 것 같습니다.

2023-07-03 13:25 UTC, HoYeonHwang commented on src/App.tsx
> +          (err) => {}
추가로 구현이 되어야 하는 부분일까요?

2023-07-03 13:25 UTC, HoYeonHwang commented on src/components/LoginPage.tsx
> +        localStorage.setItem("email", data.email);
res의 email을 로컬 스토리지에 저장하는 방법도 괜찮아 보입니다.

ex) data.email -> res.data.email

2023-07-04 07:41 UTC, gyucheolshin commented on src/components/LoginPage.tsx
> +        localStorage.setItem("pwd", data.pwd);
비밀번호는 저장 안되도록 수정하였습니다.

2023-07-04 07:44 UTC, gyucheolshin commented on src/App.tsx
> +          (err) => {}
향후 변경된 서버 api에 맞춰서 불러온 유저 정보를 저장하는 코드를 추가할 예정입니다.

2023-07-04 07:57 UTC, gyucheolshin commented on src/components/LoginPage.tsx
> +        localStorage.setItem("email", data.email);
로그인 성공 시 서버로부터 받아오는 데이터 (data : access Token, message : "로그인 성공") 가 토큰과 메세지 뿐이어서
말씀하신대로 res.data.email로 저장하려면 백엔드에서 이메일 정보를 추가해 주셔야 할 것 같습니다.

2023-07-05 07:33 UTC, merged